name = "PolyaDataStructures"
uuid = "68a5617c-cc28-44f0-83bd-8c98376c0d97"
authors = ["Michiel Van Lancker <michiel.vanlancker@cs.kuleuven.be>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
